import Layout from '@/components/Layout'
import React from 'react'
export default function AboutPageIndex() {
  return (
    <Layout>
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
        sddsfsdf
   </Layout>
  )
}
